#!/bin/bash
##PBS -A RRFS-DEV
##PBS -q dev_transfer
#PBS -l select=1:mpiprocs=1:ncpus=1
##PBS -l walltime=05:59:00
##PBS -N rrfs_a_run_archive2
##PBS -j oe -o /lfs/h2/emc/ptmp/emc.lam/archive/archive.log


module load prod_util/2.0.14

set -x

#CDATE=2023052300
#RRFSVER=v0.4.1
currentdate=$CDATE
mydate=${currentdate:0:8}
echo $mydate
hour=${currentdate:8:2}
echo $hour

ARCHIVEDIR=/NCEPDEV/emc-meso/1year/emc.lam/exp/n3v41
archive_dir=$ARCHIVEDIR/rrfs.${mydate}
proddir=/lfs/h2/emc/ptmp/emc.lam/rrfs/${RRFSVER}/prod/rrfs.${mydate}/$hour

echo $archive_dir

cd $proddir
numfile=`ls rrfs.*.prslev.f*.conus_3km.grib2 | wc | awk '{ print $1 }'`

if  [ $numfile > 1 ]; then
  mkdir tmpgrib
  cd tmpgrib

  num='00 01 02 03 04 05 06 07 08 09 10 11 12 15 18'
  long_fcst_hour="00 06 12 18"
  for ihh in $long_fcst_hour
  do 
    if [ "$hour" == $ihh ]; then
      num='00 01 02 03 04 05 06 07 08 09 10 11 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60'
    fi
  done

  for inum in $num
  do
    #cp rrfs.t${hour}z.prslev.f0${inum}.conus_3km.grib2  ./tmpgrib
    ln -f ../rrfs.t${hour}z.prslev.f0${inum}.conus_3km.grib2  .
  done

  echo $archive_dir

  hsi mkdir -p $archive_dir
  htar -chvf $archive_dir/rrfs.t${hour}z.prslev.conus_3km.grib2.tar rrfs.t${hour}z.prslev.f*.conus_3km.grib2
fi

exit

